/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactCard: typeof import('./src/components/contacts/ContactCard.vue')['default']
    ContactForm: typeof import('./src/components/contacts/ContactForm.vue')['default']
    ContactList: typeof import('./src/components/contacts/ContactList.vue')['default']
    ContactTest: typeof import('./src/components/contacts/ContactTest.vue')['default']
    'IFa6Brands:facebook': typeof import('~icons/fa6-brands/facebook')['default']
    'IFa6Brands:instagram': typeof import('~icons/fa6-brands/instagram')['default']
    'IFa6Brands:linkedinIn': typeof import('~icons/fa6-brands/linkedin-in')['default']
    'IFa6Brands:weixin': typeof import('~icons/fa6-brands/weixin')['default']
    'IFa6Brands:xTwitter': typeof import('~icons/fa6-brands/x-twitter')['default']
    'IFa6Solid:angleDown': typeof import('~icons/fa6-solid/angle-down')['default']
    'IFa6Solid:caretDown': typeof import('~icons/fa6-solid/caret-down')['default']
    'IFa6Solid:magnifyingGlass': typeof import('~icons/fa6-solid/magnifying-glass')['default']
    'IFa6Solid:plus': typeof import('~icons/fa6-solid/plus')['default']
    'IIc:baselineEmail': typeof import('~icons/ic/baseline-email')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
